### ISSUE TITLE
(JMDict English) [Errno24] Too many open files in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by AxillV** [precondition/Verb_inflections_JMDict#1]
Greetings! Thank you for this helpful script. 
I was trying to generate the files for the English dictionary, however I'm getting the following error message:
**Traceback (most recent call last):
  File "/home/user/Documents/Japanese/Verb_inflections_JMDict-main/generate_ja_conjugations.py", line 48, in <module>
  File "/home/user/Documents/Japanese/Verb_inflections_JMDict-main/generate_ja_conjugations.py", line 41, in generate_conjugated_entries
  File "/home/user/.local/lib/python3.10/site-packages/pykatsuyou/pykatsuyou.py", line 49, in getInflections
  File "/home/user/.local/lib/python3.10/site-packages/igo/tagger.py", line 72, in __init__
  File "/home/user/.local/lib/python3.10/site-packages/igo/dictionary.py", line 104, in __init__
  File "/home/user/.local/lib/python3.10/site-packages/igo/dictreader.py", line 160, in DictReader
  File "/home/user/.local/lib/python3.10/site-packages/igo/dictreader.py", line 111, in __init__
OSError: [Errno 24] Too many open files**

This is not always happening, for example using the jmdict revision 4, the term_bank_2 and 32 can be generated successfully, but the terms_banks 1 and 3 cannot. 
Their sizes are ~ 735, 503, 843, 819 kB respectively.

**dictreader.py:**
line 111:

```
def __init__(self, path, bigendian=False):
    self.fd = os.open(path, os.O_RDONLY)
    self.mmap = mmap.mmap(self.fd, length=0, access=mmap.ACCESS_READ)    #<-----------line 111
    self.view = memoryview(self.mmap)
    self.pos = 0
```
line 160:
```
def DictReader(f, b=False, use_mmap=None):
    m = allow_mmap if use_mmap is None else use_mmap
    if m:
        return MMapedReader(f, b)     #<----------line 160
    else:
        return StandardReader(f, b)```

**Comment by precondition** [comment]
The issue comes from the `pykatsuyou` dependency which recreates the `Tagger` object on every call of the `getInflections` function. Each creation of this object opens a new file descriptor (for the dictionary used by the parser).

Creating the object only once and reusing it on every call of the `getInflections` function solves the issue.
```diff
--- pykatsuyou.py	2023-09-03 15:24:02.649844637 +0200
+++ patched_pykatsuyou.py	2023-09-03 15:25
@@ -8,6 +8,8 @@
 from .iAdj import IAdj
 from .irregulars import IrregularVerb
 
+tt = Tagger()
+
 def getInflections(text: str, jsonIndent: int = 0, dataframe:bool = False):
     """
     Get the inflections of a verb or adjective.
@@ -46,7 +48,6 @@
     EXCEPTIONS = ['入る', '走る', '要る', '帰る', '限る', '切る', '喋る', '知る', '湿る', 'しゃべる', '減る', '焦る', '蹴る', '滑る', '握る', '練る', '参る', '交じる', '嘲る', '覆る', '遮る', '罵る', '捻る', '翻る', '滅入る', '蘇る']
     IRREGULARS = ['する', '為る', 'くる', '来る']
 
-    tt = Tagger()
     check = tt.parse(text)
     posDivided = check[-1].feature.split(',') if len(check) > 0 else []
```

I'll submit that patch to the `pykatsuyou` project. In the meantime, commit 9c7d1119e826fd3e86ec168d11832262c37dc7d6 includes a patched version of the pykatsuyou file so you can update your copy of `Verb_inflections_JMDict` and try again :)

**Comment by precondition** [comment]
If you're interested, I also ran the script on the JMDict English extra version with examples sentences and published it as [a release](https://github.com/precondition/Verb_inflections_JMDict/releases/tag/en_extra). Since this is the extra version, the resulting file is voluminous though.
